name: 'CI Build & Publish'

on:
    release:
        types: [published]

jobs:
    publish-npm:
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup .npmrc
              run: echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 16
                  cache: 'npm'
                  registry-url: 'https://registry.npmjs.org'

            - name: Install dependencies
              run: npm ci

            - name: Build TypeScript project with Webpack
              run: npm run build

            - name: Clean npm cache
              run: npm cache clean --force

            - name: Publish to npm
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
